theme: jekyll-theme-cayman

title: Alina Christenbury
email: alina.christenbury@gmail.com

twitter_username: AlinaWithAFace
github_username:  AlinaWithAFace

logo: /assets/img/christenbury-alina-headshot.jpg
