theme: jekyll-theme-time-machine

title: Alina Christenbury
email: alina.christenbury@gmail.com

twitter_username: AlinaWithAFace
github_username:  AlinaWithAFace

logo: /assets/img/christenbury-alina-headshot.jpg

# Build settings
markdown: kramdown